### ISSUE TITLE
Unnecessary configuration option for CSV Write

### ISSUE THREAD

**Issue by zubairov** [elasticio/csv-component#1]
When configuring CSV Write action, skip-rows option is not required:

![image](https://user-images.githubusercontent.com/56208/27782807-4c29dcae-5fd4-11e7-8e31-e0b49c341127.png)

It was needed when reading CSV file as it might contain a header row(s) that have to be ignored. When writing CSV this option is not necessary, and potentially could be replaced with the checkbox that will configure if header row would be generated or not.

**Comment by jhorbulyk** [comment]
@zubairov Can this be closed since at the moment, this component does not define any write operation?

**Comment by jhorbulyk** [comment]
Closing this in favor of #9
