### ISSUE TITLE
CSV should support dynamic metadata

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/csv-component#10]

**Comment by zubairov** [comment]
@jhorbulyk could you please check and estimate the complexity of this one

**Comment by jhorbulyk** [comment]
I looked into this.  Since the frontend is actually handling the metadata for this component this works out of the box.

**Comment by zubairov** [comment]
Wow. Does it also work? Had you tested it?

**Comment by jhorbulyk** [comment]
Because I didn't see evidence of this functionality existing in the code, I had assumed that it did not exist.  It does work if you try it out and understand that for certain components the metadata generates outside of the component.

**Comment by jhorbulyk** [comment]
I was confused.  This component does not support adding columns to the metadata.

**Comment by jhorbulyk** [comment]
PRs:
https://github.com/elasticio/csv-component/pull/14
https://github.com/elasticio/frontend/pull/2470

**Comment by jhorbulyk** [comment]
This issue has been released.
