### ISSUE TITLE
Start the process of deprecation for old branch

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/csv-component#104]
# Internal Issue/Enhancement

## Description

Please prepare a release in the v2 series with a deprecation sign. It might be a good idea to use grayscale icon for that deprecated version.

## Definition of Done

Deprecation of V2 version of the CSV component.

**Comment by A3a3e1** [comment]
https://github.com/elasticio/csv-component has been copied to the new repository https://github.com/elasticio/csv-component-v3
The old repo has been made deprecated. The history has been reset to the commit `ca1964793d1cc7f4cc95bae697d9b409a791cefd` which is actually v2.2.0 on the platform.
Previously it was a mistake in the releases where the v2.2.0 on the platform did not match with the Github release 2.2.0 as it included one more commit. It has been fixed.
All the future component development should be done in the `v3` component.
