### ISSUE TITLE
Trouble with using write csv component

### ISSUE THREAD

**Issue by luzhok** [elasticio/csv-component#13]
STR:
1. Create the first step for flow. In my case, it is Nodejs.code:
// Create message to be emitted
function send(i, name, delay) {
    setTimeout(() => {
        const data = {
            message: 'hello world',
            name,
            i
        };
        console.log('\n emitting', data);
        // Emit the data event
        emitter.emit('data', messages.newMessageWithBody(data));
    }, delay);
}

send(1, 'f-1', 100);
send(2, 'f-1', 3000);
send(3, 'f-1', 5000);

send(4, 'f-2', 16000);

send(5, 'f-3', 28000);

// No need to emit end
console.log('Finished execution');

2. Add next step - CSV-component. You can see Configure Input in the screen 
![input_csv](https://user-images.githubusercontent.com/32069340/30961928-8b2513ae-a450-11e7-93a8-00b5bae6a5d6.png)
 3. Click "Test this step"

AR: there is an error in the log and I can't finish my flow
Starting your Docker container ...
Starting application in apprunner
Not Available
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 0.01 CPU available
Starting the application with node ./node_modules/elasticio-sailor-nodejs/run.js
Initializing component for execution
Initializing component for execution
Incoming message is {"passthrough":{"step_1":{"metadata":{},"headers":{},"body":{"i":1,"name":"f-1","message":"hello world"},"attachments":{},"id":"615ecfdc-33db-4b8c-ab64-a67164b48f04"}},"metadata":{},"headers":{},"body":{"i":1,"name":"f-1","message":"hello world"},"attachments":{},"id":"615ecfdc-33db-4b8c-ab64-a67164b48f04"}
URL of the CSV is missing
Process function is a Promise/generator/etc
at TaskExec.onData (/app/node_modules/elasticio-sailor-nodejs/lib/sailor.js:227:38)
TypeError: Cannot create property 'passthrough' on boolean 'true'
at TaskExec.emit (events.js:188:7)
WARNING: End was emitted more than once!
at onPromisedData (/app/node_modules/elasticio-sailor-nodejs/lib/executor.js:31:18)
at emitOne (events.js:96:13)
at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jhorbulyk** [comment]
This was caused by me pushing to the wrong repository prior to testing.
