### ISSUE TITLE
CSV Write: We should allow users to add headers which contain spaces and capital letters

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/csv-component#15]

**Comment by zubairov** [comment]
is it? May be then close it?

**Comment by jhorbulyk** [comment]
I think the issue was that frontend code takes user input for headers with capitals and spaces and automatically removes them without any capacity to override this behavior.

**Comment by benburch** [comment]
+1 The CSV component doesn't let you define the headers, they are always transformed into lower_case_format

Needs to support this for two customers @zubairov

**Comment by zubairov** [comment]
As I support this issue it should be fixed in UI and not in the component right?

**Comment by benburch** [comment]
![screenshot 2018-12-06 13 55 44](https://user-images.githubusercontent.com/6196181/49588521-cf99b800-f95e-11e8-8a08-0219238f06b6.png)

Not sure where the naming of the attributes is defined? But ^^ is the issue.

**Comment by benburch** [comment]
Any updates on this and when a resolution might be sorted?

**Comment by jhorbulyk** [comment]
Issue moved to [elasticio/platform #630](https://github.com/elasticio/platform/issues/630) via [**ZenHub**](https://www.zenhub.com/)

**Comment by benburch** [comment]
@drobiazko moved from component onto platform. We have a work around for February, this will become harder to manage in March and onwards.
