### ISSUE TITLE
Disappeared icons of the CSV-component on the flow

### ISSUE THREAD

**Issue by luzhok** [elasticio/csv-component#17]
Precondition: flow CSV_read=>CSV_write=>SFTP exists
version of CSV=old version
STR:
1. Make git push new version of the CSV-component
2. Open our flow 

AR: Icons and settings of the CSV-steps are empty. Icor of SFTP-step is present. see the screen
![bug19](https://user-images.githubusercontent.com/32069340/32101224-fe866a92-bb1f-11e7-8037-f2e40627c919.png)
But flow is still work correct
ER: everything looks as usual

**Comment by jhorbulyk** [comment]
To elaborate, this happens when upgrading between git commit ``16469a93db743a90bd61187d616e4c0a5d81d9e7`` and ``d9c377b5f38bbcf32ab148e5b35f4fcf98411def`` of https://github.com/elasticio/csv-component/

**Comment by drobiazko** [comment]
@jhorbulyk is it a bug inside component or platform?

**Comment by jhorbulyk** [comment]
I believe that it is a platform bug.

**Comment by drobiazko** [comment]
@luzhok can you confirm it?

**Comment by luzhok** [comment]
@drobiazko I'm doing right now

**Comment by luzhok** [comment]
@drobiazko @jhorbulyk I've just checked with NodeJS - didn't reproduce. MAybe, this problem with component, but not with platform

**Comment by jhorbulyk** [comment]
I could not reproduce it either.

**Comment by luzhok** [comment]
you mean, with CSV-component?

**Comment by jhorbulyk** [comment]
> you mean, with CSV-component?

Correct.

**Comment by drobiazko** [comment]
So, the bug is a ghost?

**Comment by drobiazko** [comment]
@luzhok do we deploy it now or not?

**Comment by luzhok** [comment]
@drobiazko we are trying reproduce the bug with @jhorbulyk together. We need a minute

**Comment by luzhok** [comment]
@drobiazko we can't reproduce it. MAybe the root of the problem is 2 identical revisions. But @yarikos said - 2 identical revisions in different teams - its ok. But not in our case

**Comment by luzhok** [comment]
closed!
