### ISSUE TITLE
Test it in combination with new JSONata number formatting feature

### ISSUE THREAD

**Issue by zubairov** [elasticio/csv-component#18]
As of JSONata 1.4.1 following functionality is available:

https://github.com/jsonata-js/jsonata/issues/54

as soon as e.io mapping will adopt it (see https://github.com/elasticio/mapper/issues/18) we should test if we could use it in CSV Write - formatting numbers with e.g. '$' signs so that `10.248` would become `$10,25`

**Comment by luzhok** [comment]
I've added this case  to our tests. Thnx!

**Comment by zubairov** [comment]
great, thought we could potentially just use these new function in existing test case :) but it's up to you

**Comment by luzhok** [comment]
close the issue
