### ISSUE TITLE
Action: Read CSV attachment does not support local agents

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/csv-component#24]
**Description:** Action: Read CSV attachment does not support local agents as it uses Steward. 
[Blocked by this issue](https://github.com/elasticio/admiral/issues/315)

**STR:**
1. Create flow sftp-> CSV (Action: Read CSV attachment)
2. Select agent on second step and retrieve sample

**AR:** Sample is not retrieved, but error message is shown: `Error! Failed to retrieve data sample from the component.`

**ER:** Sample is retrieved on LA.

*Notes:*
Platform logs:
`
This process is being executed on your agent "stas_agent". Please see the logs locally.
Error: ERROR_TASK_FAILED
    at new e (https://app.elastic.io/frontend.min.js:59:20458)
    at e (https://app.elastic.io/frontend.min.js:59:19348)
    at a (https://app.elastic.io/frontend.min.js:59:22251)
    at b (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:15:4738)
    at y (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:15:4836)
    at v (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:15:4641)
    at https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:9:33813
    at invokeWithOnError (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:1:10663)
    at r.flush (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:1:11115)
    at n.flush (https://cdnjs.cloudflare.com/ajax/libs/ember.js/1.13.13/ember.min.js:1:9143)
`

Local agent logs:
`
[INFO  tini (1)] Spawned child process '/run.sh' with pid '6'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
invokeModuleFunction – init is not found
Incoming message is {"id":"01a1854e-356c-4152-b548-e0b8d7038c4a","attachments":{"CSV_SAILOR_TEST2.csv":{"url":"http://steward-service.platform.svc.cluster.local:8200/files/6f61d8e4-47d5-4153-bb92-4350eb1f5f95","size":119}},"body":{"filename":"CSV_SAILOR_TEST2.csv","size":119},"headers":{},"metadata":{},"passthrough":{"step_1":{"id":"01a1854e-356c-4152-b548-e0b8d7038c4a","attachments":{"CSV_SAILOR_TEST2.csv":{"url":"http://steward-service.platform.svc.cluster.local:8200/files/6f61d8e4-47d5-4153-bb92-4350eb1f5f95","size":119}},"body":{"filename":"CSV_SAILOR_TEST2.csv","size":119},"headers":{},"metadata":{}}}}
Found attachment key=CSV_SAILOR_TEST2.csv attachment={"url":"http://steward-service.platform.svc.cluster.local:8200/files/6f61d8e4-47d5-4153-bb92-4350eb1f5f95","size":119}
Wed, 10 Apr 2019 08:38:07 GMT csv Sending GET request to url=http://steward-service.platform.svc.cluster.local:8200/files/6f61d8e4-47d5-4153-bb92-4350eb1f5f95
Error happened: getaddrinfo ENOTFOUND steward-service.platform.svc.cluster.local steward-service.platform.svc.cluster.local:8200
Error: getaddrinfo ENOTFOUND steward-service.platform.svc.cluster.local steward-service.platform.svc.cluster.local:8200
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
[INFO  tini (1)] Main child exited normally (with status '1')
`

**Comment by jhorbulyk** [comment]
Closing since old local agents are now largely deprecated.
