### ISSUE TITLE
Make sure the SAPbyDesign Connector follows the OIH standard

### ISSUE THREAD

**Issue by juhrmacher** [elasticio/csv-component#28]
We have to make sure that SAPbyDesign Connector follows the OIH standard.
Tasks:
1.) Examine the actual state of the SAPbyDesign Connector
2.) Describe issues that need to be solved
3.) Estimate efforts

**Comment by A3a3e1** [comment]
Issue moved to [elasticio/sapbydesign-component #282](https://github.com/elasticio/sapbydesign-component/issues/282) via [**ZenHub**](https://www.zenhub.com/)
