### ISSUE TITLE
SOAP component should support the ability to generate SOAP responses given a WSDL #3

### ISSUE THREAD

**Issue by juhrmacher** [elasticio/csv-component#42]
Please refer to ...

https://github.com/openintegrationhub/soap-component/issues/3

**Comment by jhorbulyk** [comment]
The UX around this has the potential to become odd due to https://github.com/elasticio/elasticio/issues/2059

**Comment by A3a3e1** [comment]
Issue moved to [elasticio/soap-component-java #12](https://github.com/elasticio/soap-component-java/issues/12) via [**ZenHub**](https://www.zenhub.com/)
