### ISSUE TITLE
Refactor CSV using new csv parse library

### ISSUE THREAD

**Issue by hannah-bulmer** [elasticio/csv-component#46]
The `csv-parse` library is outdated and does some weird things. 
After discussion with @jhorbulyk also regarding the dictionary-component, it was decided it makes sense to revitalize the csv-component using [papaparse](https://www.papaparse.com/) as the csv parser instead.

This adds many useful features such as effective header recgonization and automatic determination of delimiter from the csv data, allowing us to simplify the metadata configuration required as well.

**Comment by jhorbulyk** [comment]
Closing in favor of #95, #96 & #97
