### ISSUE TITLE
Improve CSV Write functionality

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/csv-component#5]
The CSV write functionality should do the following:
1. The component should produce a message with an attachment.  The attachment should be a link to the CSV file.
1. In the configuration, the user is able to define the CSV's header columns as well as the type for each column.
1. The component should place multiple inbound events in the same CSV file (attachment). Event sequence end should be determined based on the inactivity timeout.
1. ~The cells in the CSV file should be appropriately formatted based on the set type for the column.  This formatting should be set so that Excel users in various locals (USA & Germany) can easily open the file.~

**Comment by zubairov** [comment]
I would suggest to do the formatting requirement:

> The cells in the CSV file should be appropreately formatted based on the set type for the column. This formatting should be set so that Excel users in various locals (USA & Germany) can easily open the file.

in different enhancement

**Comment by jhorbulyk** [comment]
So ignore all the logic and mechanisms that we have for column formatting?

**Comment by zubairov** [comment]
Yes, this issue would be simpler to solve if it has a smaller scope
