### ISSUE TITLE
Fix helper actions links

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/csv-component#61]
Fix needed for actions:
- Write CSV attachment from JSON Object 
- Write CSV attachment from JSON Array

Currently, it leads to a valid CSV component page but does not scroll to a proper action section

![image](https://user-images.githubusercontent.com/36419533/79849031-997d9c80-83ca-11ea-87e2-9a7c2d8aa777.png)

**Comment by kirill-levitskiy** [comment]
The PR contains required fixes: https://github.com/elasticio/csv-component/pull/63
