### ISSUE TITLE
Default value cannot be set as 'Include Headers' field is required  

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/csv-component#62]
Issue valid for actions:

- Write CSV attachment from JSON Object
- Write CSV attachment from JSON Array

![image](https://user-images.githubusercontent.com/36419533/79849912-ce3e2380-83cb-11ea-8080-b59a74bae45f.png)

AR: Error thrown on sample retrieve attempt if no option selected 
ER: 
- 'Include Headers' is not required 
**OR**
- 'Include Headers' field is required and placeholder is changed: `Include headers? Default Yes` -> `Include headers?`

**Comment by kirill-levitskiy** [comment]
The PR contains required fixes: https://github.com/elasticio/csv-component/pull/63
