### ISSUE TITLE
CSV component when displaying the header which contains number in the text. *(add _ between the text and number) 

### ISSUE THREAD

**Issue by shadyhsoliman** [elasticio/csv-component#83]
The client is having trouble when configuring the Headers as a string the component automatically creates (_) space between the text and the number 
as an example 

The CSV contains sch_h2 which in the sample data the header turns to "sch_h_2". When the user saves the sample with "sch_h_2". This confuses the user and also causes difficulty to map the correct header at any following steps. 

here's a step for replication.

![image](https://user-images.githubusercontent.com/77006533/108511649-7e1c4000-72c0-11eb-8481-8f9642e863b8.png)
![image](https://user-images.githubusercontent.com/77006533/108511690-8aa09880-72c0-11eb-8d7f-0594a3bbb2f5.png)

**Comment by shadyhsoliman** [comment]
https://dev.mq.edu.au/__data/assets/text_file/0019/1054063/MQU-Scholarships-SAMPLE.csv

**Comment by denyshld** [comment]
Looks like platform issue. Existing CSV view uses _.snakeCase(...) to generate header name:

Code:
```
const _ = require('lodash');
const property = _.snakeCase('sch_h2 ');
console.log(property);
```
Output: sch_h_2

Code line: https://github.com/elasticio/elasticio/blob/5d6117b21bb8e7443c0e7c75d96d4dd1a1ff30d1/src/frontend/src/modules/react/components/fields/csv-view.jsx#L61

**Comment by jhorbulyk** [comment]
Closing in favor of #96 & #97
