### ISSUE TITLE
CSV written with invalid data type

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/csv-component#88]
Description: usage new library instead of current one should probably fix this behavior: https://github.com/elasticio/csv-component/issues/46

STR: 
1. write file, input:
CSV Header*: MATERIAL,GRID,NAME,WHOLESALE,CURRENCY,ATP,ATS,IS_NEW_MATERIAL,QUANTITY,,,,,,,,,,IMAGE,,
all data types are default except for: 
![image](https://user-images.githubusercontent.com/36419533/109956535-6f844e80-7cec-11eb-96c9-dcf6653bade9.png)
2. retrieve sample
3. add next step with Read action: use same headers and data types as in write CSV action
4. retrieve sample
AR: 
{
  "material": "wdwedwe",
  "grid": "uyuuiiuiu",
  "name": "iujuijiujuih",
  "wholesale": "iyuyuyunh",
  "currency": "ewcweciu",
  "atp": "uiyiuyuy",
  "ats": "yuiyuyuiyui",
  "is_new_material": "uiyuiyuyiu",
  "quantity": "uuhuihuh",
  "column_9": "ntntnt",
  "column_10": "",
  "column_11": "tytyf",
  "column_12": "tyfytft",
  "column_13": "tfyf",
  "column_14": 1234567,
  "column_15": "1",
  "column_16": "",
  "column_17": "hghg",
  "image": "vgvgv",
  "column_19": "7887787y7h",
  "column_20": "~!@#$%^&*()"
}

ER:

{
  "material": "wdwedwe",
  "grid": "uyuuiiuiu",
  "name": "iujuijiujuih",
  "wholesale": "iyuyuyunh",
  "currency": "ewcweciu",
  "atp": "uiyiuyuy",
  "ats": "yuiyuyuiyui",
  "is_new_material": "uiyuiyuyiu",
  "quantity": "uuhuihuh",
  "column_9": "ntntnt",
  "column_10": "",
  "column_11": "tytyf",
  "column_12": "tyfytft",
  "column_13": "tfyf",
  "column_14": 1234567,
  "column_15": true,
  "column_16": false,
  "column_17": "hghg",
  "image": "vgvgv",
  "column_19": "7887787y7h",
  "column_20": "~!@#$%^&*()"
}

**Comment by jhorbulyk** [comment]
Hopefully would become deprecated by work in #96 & #97 .

**Comment by jhorbulyk** [comment]
Resolved by V3 of the component.
